# Copyright 2026 Elementum Ltd. All Rights Reserved.
# Licensed under the Apache License, Version 2.0

version: 2

project_name: ei

builds:
  - main: .
    binary: ei
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: tar.gz
    name_template: "ei_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true
