# Agent mutations

mutation CreateAgent($input: AgentCreateV3Input!) {
  agentCreateV3(input: $input) {
    __typename
    id
    name
    description
    ... on AgentElementum {
      agentAuthentication {
        jwt {
          enabled
          emailAddressClaimName
          headerName
          keySource {
            __typename
            ... on AgentAuthenticationJwtPlainTextSource {
              plainTextKeyValuePem
            }
            ... on AgentAuthenticationJwtJwksSource {
              jwksUrl
            }
          }
          requiredClaims {
            claimName
            acceptableValues
          }
        }
      }
    }
  }
}

mutation UpdateAgent($id: ID!, $input: AgentUpdateV2Input!) {
  agentUpdateV2(id: $id, input: $input) {
    __typename
    id
    name
    description
    ... on AgentElementum {
      agentAuthentication {
        jwt {
          enabled
          emailAddressClaimName
          headerName
          keySource {
            __typename
            ... on AgentAuthenticationJwtPlainTextSource {
              plainTextKeyValuePem
            }
            ... on AgentAuthenticationJwtJwksSource {
              jwksUrl
            }
          }
          requiredClaims {
            claimName
            acceptableValues
          }
        }
      }
    }
  }
}

mutation DeleteAgent($id: ID!) {
  agentDelete(id: $id) {
    id
  }
}

mutation CreateAgentTool($agentId: ID!, $input: AgentToolCreateInput!) {
  agentToolCreate(agentId: $agentId, input: $input) {
    id
    name
    description
  }
}

mutation UpdateAgentTool($id: ID!, $input: AgentToolUpdateInput!) {
  agentToolUpdate(id: $id, input: $input) {
    id
    name
    description
  }
}

mutation DeleteAgentTool($id: ID!) {
  agentToolDelete(id: $id) {
    id
  }
}
